public with sharing class C {

    public static String LIGHTNING_REPORTER_PERMISSION{
        get{
            return 'Lightning_Reporter';
        }
    }
    
    public static String USAGE_PIN{
        get {
            return 'Pin Layout';
        }
    }

    public static String USAGE_COMMENT{
        get {
            return 'Comment';
        }
    }

    public static String USAGE_SAVE{
        get {
            return 'Save Records';
        }
    }
}
